<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Add new controller</h3>
            </div>
            <form method="post" role="form">
                <div class="box-body">
                    <div class="form-group">
                        <label for="controller_base_url">Base URL</label>
                        <input required name="controller_base_url" type="text" class="form-control" id="controller_base_url" placeholder="https://unifi.babb.tech:8443">
                    </div>
                    <div class="form-group">
                        <label for="controller_username">Username</label>
                        <input required name="controller_username" type="text" class="form-control" id="controller_username" placeholder="">
                    </div>
                    <div class="form-group">
                        <label for="controller_password">Password</label>
                        <input required name="controller_password" type="password" class="form-control" id="controller_password" placeholder="">
                    </div>
                    <div class="form-group">
                        <label for="controller_version">Version</label>
                        <input required name="controller_version" type="text" class="form-control" id="controller_version" placeholder="4.8.3">
                    </div>
                </div>
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Add my controller</button>
                </div>
            </form>
        </div>
    </div>
</div>
