<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Add new controller</h3>
            </div>
            <form id="controller-create" method="post" role="form">
                <div class="box-body">
                    <div class="form-group">
                        <label for="base_url">Base URL</label>
                        <input required name="base_url" type="text" class="form-control" id="base_url" placeholder="https://unifi.babb.tech:8443">
                    </div>
                    <div class="form-group">
                        <label for="username">Username</label>
                        <input required name="username" type="text" class="form-control" id="username" placeholder="">
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input required name="password" type="password" class="form-control" id="password" placeholder="">
                    </div>
                </div>
                <div class="box-footer">
                    <button type="submit" onclick="createController(); return false;" class="btn btn-primary">Continue</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>

    function createController() {

        var formData = JSON.stringify($("#controller-create").serializeArray());

        $.ajax({
            type: "POST",
            url: "/client/controller/create",
            data: formData,
            dataType: "json",
            contentType : "application/json"
        }).done(function(result) {
            processMessage(result);
        }).fail(function(xhr, status, error) {
            processMessage(xhr.responseJSON);
        });
    }

</script>

