<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Add new controller</h3>
            </div>
            <form method="post" role="form">
                <div class="box-body">
                    <div class="form-group">
                        <label for="base_url">Base URL</label>
                        <input required name="base_url" type="text" class="form-control" id="base_url" placeholder="https://unifi.babb.tech:8443">
                    </div>
                    <div class="form-group">
                        <label for="username">Username</label>
                        <input required name="username" type="text" class="form-control" id="username" placeholder="">
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input required name="password" type="password" class="form-control" id="password" placeholder="">
                    </div>
                    <div class="form-group">
                        <label for="version">Version</label>
                        <input required name="version" type="text" class="form-control" id="version" placeholder="4.8.3">
                    </div>
                </div>
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Continue</button>
                </div>
            </form>
        </div>
    </div>
</div>


