<div class="row">
    <div class="col-md-8">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Edit my authentication</h3>
            </div>
            <form id="controller-update" method="post" role="form">
                <div class="box-body">
                    <div class="form-group">
                        <label for="base_url">Base URL</label>
                        <input required name="base_url" type="text" class="form-control" id="base_url" value="<?=$this->controller['base_url']?>" >
                    </div>
                    <div class="form-group">
                        <label for="username">Username</label>
                        <input required name="username" type="text" class="form-control" id="username" value="<?=$this->controller['username']?>">
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input required name="password" type="password" class="form-control" id="password" value="<?=$this->controller['password']?>">
                    </div>
                </div>
                <div class="box-footer">
                    <button  onclick="updateController(); return false;" type="submit" class="btn btn-primary">Update Controller Settings</button>
                </div>
            </form>
        </div>
    </div>

    <div id="sites" class="col-md-4">

    </div>

</div>

<script>
    $(document).ready(function() {
            $.ajax({
                type: "GET",
                url: "/client/controller/view/<?=$this->controller['id']?>",
                dataType: "json",
                contentType : "application/json"
            }).then(function(data) {
                var response = data.data;
                $.each(response.controller.sites, function(k, v) {
                    var site =  response.controller.sites[k];
                    var block = '';

                    block += '<div class="box box-widget widget-user-2">';
                    block += '<div class="widget-user-header bg-blue">';
                    block += '<div class="widget-user-image">';
                    block += '<img  src="https://cdn2.iconfinder.com/data/icons/free-mobile-icon-kit/64/Site_Map.png" alt="Site">';
                    block += '</div>';
                    block += '<h3 class="widget-user-desc">Site: ' + site['site_name'] + '</h3>';
                    block += '</div>';

                    block += '<div class="box-footer no-padding">';
                    block += '<ul class="nav nav-stacked">';

                    var validation = function () {
                        var messages;
                        $.ajax({
                            type: "GET",
                            url: "/client/site/validate/" + site['id'],
                            dataType: "json",
                            contentType : "application/json"
                        }).success(function(data) {
                            var response = data.data;
                            messages = response.messages.errors;
                            return messages;
                        });
                    };

                    console.log(validation);
                    if(validation instanceof Array) {
                        $.each(validation, function(k, v) {
                            block += '<div style="padding-left: 10px; padding-right: 10px;padding-top: 10px;" class="form-group">';
                            block += '<span style="color: red;">' + v + '</span>';
                            block += '</div>';
                        });
                    }

                    block += '<form id="site-portal-update">';
                    block += '<div style="padding-left: 10px; padding-right: 10px;padding-top: 10px;" class="form-group">';
                    block += '<select onchange="updateSitePortal(' + site['id'] + ');" name="portal" class="form-control select2" style="width: 100%;">';
                    block += '<option selected="selected">Select a Portal (No portal assigned)</option>';

                    $.each(response.portals, function(kp, portal) {
                        if(site['portal_id'] == portal.id){
                            block += '<option selected value="' + portal.id + '">' + portal.title + '</option>';
                        } else {
                            block += '<option value="' + portal.id + '">' + portal.title + '</option>';
                        }
                    });

                    block += '</select>';
                    block += '</div>';
                    block += '</form>';

                    $.each(site.aps, function(k, v) {
                        var ap = site.aps[k];
                        if(ap['uptime']){
                            block += '<li><a href="#">' + ap['mac'] + ' - ' + ap['model'] + '<span class="pull-right badge bg-green">Online</span></a></li>';
                        } else {
                            block += '<li><a href="#">' + ap['mac'] + ' - ' + ap['model'] + '<span class="pull-right badge bg-red">Offline</span></a></li>';
                        }
                    });

                    block += '</ul>';
                    block += '</div>';
                    block += '</div>';

                    $('#sites').append(block);

                });
            });
    });
</script>



<script>

    function updateSitePortal(id) {

        var formData = JSON.stringify($("#site-portal-update").serializeArray());

        $.ajax({
            type: "POST",
            url: "/client/site/update-portal/" + id,
            data: formData,
            dataType: "json",
            contentType : "application/json"
        }).done(function(result) {
            processMessage(result);
        }).fail(function(xhr, status, error) {
            processMessage(xhr.responseJSON);
        });

    }

    function updateController() {

        var formData = JSON.stringify($("#controller-update").serializeArray());

        $.ajax({
            type: "POST",
            url: "/client/controller/update/<?=$this->data['id']?>",
            data: formData,
            dataType: "json",
            contentType : "application/json"
        }).done(function(result) {
            processMessage(result);
        }).fail(function(xhr, status, error) {
            processMessage(xhr.responseJSON);
        });
    }

    function validate(formData, jqForm, options) {
        var form = jqForm[0];

        //Validate IP ADDRESS
        var ipRegex = /^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$/;
        if(!ipRegex.test(form.custom_ip.value)){
            processFormValidationError('Incorrect Custom IP format');
            return false;
        }

    }

</script>


<script>

    function testControllerConnection() {
        $.get( "/client/api/test-connection/<?=$this->data['id']?>")
            .done(function( data ) {
                alert( "Response: " + data.message );
            });
    }

</script>
