<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Edit my controller</h3>
            </div>
            <form method="post" role="form">
                <div class="box-body">
                    <div class="form-group">
                        <label for="base_url">Base URL</label>
                        <input required name="base_url" type="text" class="form-control" id="base_url" value="<?=$this->data['base_url']?>" >
                    </div>
                    <div class="form-group">
                        <label for="username">Username</label>
                        <input required name="username" type="text" class="form-control" id="username" value="<?=$this->data['username']?>">
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input required name="password" type="password" class="form-control" id="password" value="<?=$this->data['password']?>">
                    </div>
                    <div class="form-group">
                        <label for="version">Version</label>
                        <input required name="version" type="text" class="form-control" id="version" value="<?=$this->data['version']?>">
                    </div>

                    <div class="form-group">

                        <? if($this->data['site'] == null || $this->data['site'] == "null"): ?>
                            <div class="callout callout-info">
                                <h4>Important Notice!</h4>

                                <p>You must select a site to use for this controller</p>
                            </div>
                        <? endif; ?>

                            <label for="site">Site</label>
                        <select name="site" class="form-control select2" style="width: 100%;" title="">
                            <option value="null">Please select a site</option>
                            <? foreach($this->data['panel']['sites'] as $site): ?>
                                <option <? if($this->data['site'] == $site->name) echo "selected" ?> value="<?=$site->name?>"><?= $site->name . ' - ' . $site->desc ?></option>
                            <? endforeach; ?>
                        </select>
                    </div>

                </div>
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Update Controller Settings</button>
                    <button type="submit" class="btn btn-info" onclick="testControllerConnection(); return false;">Test controller connection</button>
                </div>
            </form>
        </div>
    </div>
</div>


<script>
    function testControllerConnection() {
        $.get( "/client/api/test-connection/<?=$this->data['id']?>")
            .done(function( data ) {
                alert( "Response: " + data.message );
            });
    }
</script>
