<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Create New Portal</h3>
            </div>
            <form role="form">
                <div class="box-body">
                    <div class="form-group">
                        <label for="portal_url">Portal URL</label>
                        <input name="portal_url" type="text" class="form-control" id="portal_url" placeholder="something.babb.tech">
                    </div>
                    <div class="form-group">
                        <label for="portal_other">Other Information</label>
                        <input name="portal_other" type="text" class="form-control" id="portal_other" placeholder="">
                    </div>
                    <div class="box-body pad">
                        <label for="portal_tos">Terms of Service</label>
                        <textarea name="portal_tos" class="textarea" placeholder="Terms of Service" style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"></textarea>
                    </div>

                </div>
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Create Portal</button>
                </div>
            </form>
        </div>
    </div>
</div>
