<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Create New Portal</h3>
            </div>
            <form id="portal-create" method="post" role="form">
                <div class="box-body">

                    <div class="form-group">
                        <label for="subdomain">Portal Subdomain</label>
                        <input name="subdomain" type="text" class="form-control" id="subdomain" placeholder="" value="">
                    </div>

                    <div class="form-group">
                        <label for="title">Portal Title</label>
                        <input name="title" type="text" class="form-control" id="title" placeholder="" value="">
                    </div>

                    <div class="form-group">
                        <label for=auth_types[]">Authentication Method(s)</label>
                        <select name="auth_types[]" class="form-control select2" multiple="multiple" data-placeholder="Select at least one authentication method" style="width: 100%;">
                            <option <? if($this->data['auth_types'] == 'automatic_authentication') echo 'selected'?> value="automatic_authentication">Automatic Authentication</option>
                            <option <? if($this->data['auth_types'] == 'button_authentication') echo 'selected'?> value="button_authentication">Single Button Authentication</option>
                            <option disabled="disabled" <? if($this->data['auth_types'] == 'voucher_authentication') echo 'selected'?> value="voucher_authentication">Voucher Authentication</option>
                            <option disabled="disabled" <? if($this->data['auth_types'] == 'username_password_authentication') echo 'selected'?> value="username_password_authentication">User Registration Authentication</option>
                            <option disabled="disabled" <? if($this->data['auth_types'] == 'custom_data_authentication') echo 'selected'?> value="custom_data_authentication">Custom Data Authentication</option>
                            <option disabled="disabled" <? if($this->data['auth_types'] == 'social_media_authentication') echo 'selected'?> value="social_media_authentication">Social Media Authentication</option>
                            <option disabled="disabled" <? if($this->data['auth_types'] == 'payment_authentication') echo 'selected'?> value="payment_authentication">Payment Authentication</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="header">Portal Header</label>
                        <textarea name="header" id="header"></textarea>
                    </div>


                </div>
                <div class="box-footer">
                    <button onclick="createPortal(); return false;" type="submit" class="btn btn-primary">Create Portal</button>
                </div>
            </form>
        </div>
    </div>
</div>


<script>

    function createPortal() {

        var formData = JSON.stringify($("#portal-create").serializeArray());

        $.ajax({
            type: "POST",
            url: "/client/portal/create",
            data: formData,
            dataType: "json",
            contentType : "application/json"
        }).done(function(result) {
            processMessage(result);
        }).fail(function(xhr, status, error) {
            processMessage(xhr.responseJSON);
        });
    }


    $(document).ready(function() {

        //Initialize Select2 Elements
        $(".select2").select2();

        //Colorpicker
        $(".my-colorpicker1").colorpicker();
        //color picker with addon
        $(".my-colorpicker2").colorpicker();

        //normal editor
        var toolbar = [
            ['style', ['style', 'bold', 'italic', 'underline', 'strikethrough', 'clear']],
            ['fonts', ['fontsize', 'fontname']],
            ['color', ['color']],
            ['undo', ['undo', 'redo', 'help']],
            ['ckMedia', ['ckImageUploader', 'ckVideoEmbeeder']],
            ['misc', ['link', 'picture', 'table', 'hr', 'codeview', 'fullscreen']],
            ['para', ['ul', 'ol', 'paragraph', 'leftButton', 'centerButton', 'rightButton', 'justifyButton', 'outdentButton', 'indentButton']],
            ['height', ['lineheight']]
        ];
        $('#header').summernote({
            toolbar: toolbar,
            height: 300,
            minHeight: 100,
            defaultBackColor: '#e0e0e0'
        });

    });

</script>
