<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Create New Portal</h3>
            </div>
            <form method="post" role="form">
                <div class="box-body">

                    <div class="form-group">
                        <label for="subdomain">Portal Subdomain</label>
                        <input name="subdomain" type="text" class="form-control" id="subdomain" placeholder="" value="<?=$this->data['subdomain']?>">
                    </div>

                    <div class="form-group">
                        <label for="title">Portal Title</label>
                        <input name="title" type="text" class="form-control" id="title" placeholder="" value="<?=$this->data['title']?>">
                    </div>

                    <div class="form-group">
                        <label for="portal_auth_types">Authentication Method(s)</label>
                        <select name="portal_auth_types[]" class="form-control select2" multiple="multiple" data-placeholder="Select at least one authentication method" style="width: 100%;">
                            <option <? if($this->data['auth_types'] == 'automatic_authentication') echo 'selected'?> value="automatic_authentication">Automatic Authentication</option>
                            <option <? if($this->data['auth_types'] == 'button_authentication') echo 'selected'?> value="button_authentication">Single Button Authentication</option>
                            <option <? if($this->data['auth_types'] == 'voucher_authentication') echo 'selected'?> value="voucher_authentication">Voucher Authentication</option>
                            <option <? if($this->data['auth_types'] == 'username_password_authentication') echo 'selected'?> value="username_password_authentication">User Registration Authentication</option>
                            <option <? if($this->data['auth_types'] == 'custom_data_authentication') echo 'selected'?> value="custom_data_authentication">Custom Data Authentication</option>
                            <option <? if($this->data['auth_types'] == 'social_media_authentication') echo 'selected'?> value="social_media_authentication">Social Media Authentication</option>
                            <option <? if($this->data['auth_types'] == 'payment_authentication') echo 'selected'?> value="payment_authentication">Payment Authentication</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="portal_header">Portal Header</label>
                        <div id="summernote"><?=$this->data['header']?></div>
                    </div>


                    <!--div class="form-group">
                        <div class="box-body pad">
                            <label for="portal_heading">Portal Heading</label>
                            <textarea name="portal_heading" class="textarea" placeholder="Portal Heading" style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"></textarea>
                        </div>
                    </div-->


                </div>
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Create Portal</button>
                </div>
            </form>
        </div>
    </div>
</div>


<script>
    $(document).ready(function() {

        //Initialize Select2 Elements
        $(".select2").select2();

        //Colorpicker
        $(".my-colorpicker1").colorpicker();
        //color picker with addon
        $(".my-colorpicker2").colorpicker();

        //normal editor
        var toolbar = [
            ['style', ['style', 'bold', 'italic', 'underline', 'strikethrough', 'clear']],
            ['fonts', ['fontsize', 'fontname']],
            ['color', ['color']],
            ['undo', ['undo', 'redo', 'help']],
            ['ckMedia', ['ckImageUploader', 'ckVideoEmbeeder']],
            ['misc', ['link', 'picture', 'table', 'hr', 'codeview', 'fullscreen']],
            ['para', ['ul', 'ol', 'paragraph', 'leftButton', 'centerButton', 'rightButton', 'justifyButton', 'outdentButton', 'indentButton']],
            ['height', ['lineheight']]
        ];
        $('#summernote').summernote({
            toolbar: toolbar,
            height: 300,
            minHeight: 100,
            defaultBackColor: '#e0e0e0'
        });

    });

</script>